name: Scheduled Post
on:
  schedule:
    - cron: "0 13 * * *" # Runs at 8:00 AM EST (13:00 UTC)

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Print the exact UTC time when the workflow starts
      - name: Print execution time
        run: date -u

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Crossposting Script
        env:
          TX_ACCESS_TOKEN: ${{ secrets.TX_ACCESS_TOKEN }}
          TX_ACCESS_TOKEN_SECRET: ${{ secrets.TX_ACCESS_TOKEN_SECRET }}
          TX_API_CONSUMER_KEY: ${{ secrets.TX_API_CONSUMER_KEY }}
          TX_CONSUMER_SECRET: ${{ secrets.TX_CONSUMER_SECRET }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
        run: node index.js